version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        VITE_BASE_URL: ${VITE_BASE_URL:-https://api.example.com}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BASE_URL=${VITE_BASE_URL:-http://localhost:3000}
    restart: unless-stopped
