version: "3.8"

services:
  # Development Frontend with Hot Reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: form-farsi-builder-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_BASE_URL=http://localhost:3000
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    stdin_open: true
    tty: true
    command: npm run dev

  # Optional: Development database
  # database-dev:
  #   image: postgres:14-alpine
  #   container_name: form-farsi-db-dev
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: form_builder_dev
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: development
  #   volumes:
  #     - postgres_dev_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#   postgres_dev_data:
