version: "3.8"

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: form-farsi-builder
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      # Optional: Mount nginx logs
      - ./logs/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: If you have a backend API
  # backend:
  #   image: your-backend-image:latest
  #   container_name: form-farsi-backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=your-database-url
  #   networks:
  #     - app-network
  #   restart: unless-stopped

  # Optional: Database (if needed)
  # database:
  #   image: postgres:14-alpine
  #   container_name: form-farsi-db
  #   environment:
  #     POSTGRES_DB: form_builder
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: your-password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge
# volumes:
#   postgres_data:
